# Generated by Django 4.2.13 on 2024-07-15 00:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntosBelen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('distrito', models.CharField(max_length=254, null=True)),
                ('incidente', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
