# Generated by Django 4.2.13 on 2024-07-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntosbelen',
            name='objid',
            field=models.IntegerField(null=True),
        ),
    ]
