# Generated by Django 4.2.13 on 2024-07-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_backend', '0003_remove_puntosbelen_objectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntosbelen',
            name='objid',
        ),
        migrations.AddField(
            model_name='puntosbelen',
            name='indicadorid',
            field=models.BigIntegerField(null=True),
        ),
    ]
